default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: article_development
  username: "manomoybiswas"
  password: "root"

test:
  <<: *default
  database: article_test
  username: "manomoybiswas"
  password: "root"

production:
  <<: *default
  database: article_production
  username: Article
  password: <%= ENV['ARTICLE_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
